REL-610971 not valid file paths are reported as a skipped file
relativityone/azure-storage-net-data-movement pull request #1
Opened 2021-11-05 10:04 UTC by mmkowal-rel

Exposed IsPathValidAsync callback through the TransferContext so customer I able to inject own code to perform validation.
Given callback is executed by SyncTransferController which is responsible for processing each chunk of file being transferred.
Given callback is executed only when set. When it is null no execution it means that no validation at all
Only source path is being validated.
When IsPathValidAsync returns true given chunk of data is being processed otherwise  TransferInvalidPathException is thrown and additionally total number of skipped files is incremented. Given path is reported through FileSkipped event

2021-11-08 10:00 UTC, KlaudiuszBryjaRelativity submitted a review, later dismissed

2021-11-23 15:09 UTC, KlaudiuszBryjaRelativity requested changes

2021-11-23 15:09 UTC, KlaudiuszBryjaRelativity commented on lib/TransferControllers/SyncTransferController.cs
> +		        {
Please fix formatting

2021-12-03 12:06 UTC, mmkowal-rel commented
As this is only PoC I'm going to close given PR without merge

2021-12-03 12:06 UTC, closed without merging