REL-620315
relativityone/azure-storage-net-data-movement pull request #15
Opened 2021-12-08 17:10 UTC by Pawel-Andruszkiewicz-Relativity

2021-12-09 08:16 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +	$NugetApiKeyName = "UnarmedTapirsNugetApiKey"
Do we need to change it while publishing?

2021-12-09 08:17 UTC, KlaudiuszBryjaRelativity approved these changes

2021-12-09 09:56 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +	$buildNupkg = $BuildConfig -eq "Release" ? "BuildNupkg.cmd" : "buildDebugNupkg.cmd"
This error occurred
```
~Unexpected token '?' in expression or statement.net-data-movement\psakefile.ps1:215 char:43
```
while executing:
```
.\build.ps1 Compile
```

2021-12-09 09:57 UTC, KlaudiuszBryjaRelativity requested changes
While executing compile task error occurred. More information in comment.

2021-12-09 10:46 UTC, Pawel-Andruszkiewicz-Relativity commented on psakefile.ps1
> +	$NugetApiKeyName = "UnarmedTapirsNugetApiKey"
No, it always stays the same.

2021-12-09 11:18 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +	$buildNupkg = $BuildConfig -eq "Release" ? "BuildNupkg.cmd" : "buildDebugNupkg.cmd"
It is because I have older version of PowerShell. At least **7.0** is necessary for ternary operators.

2021-12-09 11:19 UTC, KlaudiuszBryjaRelativity approved these changes

2021-12-09 11:32 UTC, Pawel-Andruszkiewicz-Relativity commented on psakefile.ps1
> +	$buildNupkg = $BuildConfig -eq "Release" ? "BuildNupkg.cmd" : "buildDebugNupkg.cmd"
Verified offline, you need PowerShell 7.0.0 to make it work (documentation is updated to reflect this requirement).

2021-12-10 09:42 UTC, BartoszWierzbaRelativity commented
I get an error from ./build.ps1 compile.

PS C:\SourceCode\azure-storage-net-data-movement> ./build.ps1 compile
WARNING: Unable to resolve package source 'https://relativity.jfrog.io/relativity/api/nuget/official-powershell-remote'.
WARNING: Unable to resolve package source 'https://relativity.jfrog.io/relativity/api/nuget/powershell-local'.
PackageManagement\Save-Package : No match was found for the specified search criteria and module name 'PSBuildTools'. Try
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1598 char:21
+             $null = PackageManagement\Save-Package @PSBoundParameters
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage

2021-12-10 09:53 UTC, BartoszWierzbaRelativity requested changes
I get an error from ./build.ps1 compile.

2021-12-10 11:28 UTC, BartoszWierzbaRelativity commented
> I get an error from ./build.ps1 compile.

Works on powershell 7.

2021-12-10 11:30 UTC, BartoszWierzbaRelativity approved these changes

2021-12-10 11:31 UTC, Pawel-Andruszkiewicz-Relativity commented
> I get an error from ./build.ps1 compile.
> 
> PS C:\SourceCode\azure-storage-net-data-movement> ./build.ps1 compile WARNING: Unable to resolve package source 'https://relativity.jfrog.io/relativity/api/nuget/official-powershell-remote'. WARNING: Unable to resolve package source 'https://relativity.jfrog.io/relativity/api/nuget/powershell-local'. PackageManagement\Save-Package : No match was found for the specified search criteria and module name 'PSBuildTools'. Try Get-PSRepository to see all available registered module repositories. At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1598 char:21
> 
> * ```
>           $null = PackageManagement\Save-Package @PSBoundParameters
>   ```
> * ```
>                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
>   * FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage

Discussed offline, problem with Bartek's environment.

2021-12-10 11:38 UTC, mmkowal-rel submitted a review, later dismissed

2021-12-10 11:38 UTC, mmkowal-rel commented on psakefile.ps1
> +			("-verbosity:quiet"),
what do you think about increased verbosity ? might be useful

2021-12-10 11:38 UTC, mmkowal-rel commented on tools/nupkg/Microsoft.Azure.Storage.DataMovement.nuspec
> +    <tags>Relativity, Transfer API, Azure, ADLS, Blob, Fileshare, DataMovement, Upload, Download</tags>
remove ADLS

2021-12-10 11:38 UTC, mmkowal-rel commented on DataMovement.sln
> +		tools\nupkg\Microsoft.Azure.Storage.DataMovement.nuspec = tools\nupkg\Microsoft.Azure.Storage.DataMovement.nuspec
what does this assignment do ?

2021-12-10 11:38 UTC, mmkowal-rel commented on tools/AssemblyInfo/SharedAssemblyInfo.cs
> +[assembly: AssemblyFileVersion("3.0.0-pre.1")]
should this number be changed prior the build/release or it will be updated automatically ?

2021-12-10 11:49 UTC, Pawel-Andruszkiewicz-Relativity commented on tools/AssemblyInfo/SharedAssemblyInfo.cs
> +[assembly: AssemblyFileVersion("3.0.0-pre.1")]
Yes.

2021-12-10 11:50 UTC, Pawel-Andruszkiewicz-Relativity commented on tools/AssemblyInfo/SharedAssemblyInfo.cs
> +[assembly: AssemblyFileVersion("3.0.0-pre.1")]
It will be updated automatically when you change version in `version.txt` and then invoke `build.ps1 package`. It should be committed afterwards, as that's how MS has done it (didn't want to change it too much).

2021-12-10 11:51 UTC, Pawel-Andruszkiewicz-Relativity commented on DataMovement.sln
> +		tools\nupkg\Microsoft.Azure.Storage.DataMovement.nuspec = tools\nupkg\Microsoft.Azure.Storage.DataMovement.nuspec
Simply adds nuspec file to `Solution Items` directory in Visual Studio view, nothing more.

2021-12-10 11:56 UTC, Pawel-Andruszkiewicz-Relativity commented on tools/nupkg/Microsoft.Azure.Storage.DataMovement.nuspec
> +    <tags>Relativity, Transfer API, Azure, ADLS, Blob, Fileshare, DataMovement, Upload, Download</tags>
Done.

2021-12-10 11:58 UTC, Pawel-Andruszkiewicz-Relativity commented on psakefile.ps1
> +			("-verbosity:quiet"),
Usually we don't really need it, as it's really spammy. If something breaks then you still get a meaningful error message. It may be useful only if the issue is really nuanced, but then changing the verbosity manually is easy to change just for troubleshooting.

2021-12-10 12:56 UTC, KamilKalitaRel approved these changes

2021-12-10 12:58 UTC, mmkowal-rel approved these changes

2021-12-10 12:59 UTC, merged