REL-692519 journal deserialization issue
relativityone/azure-storage-net-data-movement pull request #23
Opened 2022-06-08 13:01 UTC by KlaudiuszBryjaRelativity

2022-06-08 13:20 UTC, KlaudiuszBryjaRelativity commented on lib/TransferJobs/Transfer.cs
> -            if (!string.Equals(Constants.FormatVersion, OriginalFormatVersion, StringComparison.Ordinal))
I need to comment this part.

Library uses 2 serializers:

- `net4xx` uses a binary serializer. In that case special constructor is executed `protected Transfer(SerializationInfo info, StreamingContext context)` which uses `StreamingContext` instance to pass some data to a deserializing process. I use this to pass the flag value to the process (using `StreamJournal` instance. This allow disable version validation.
- `netstandard2.0` uses `DataContractSerializer`. In that case, no `.ctor` is executed but when deserialization if finished, a callback is executed (a method decorated with `OnDeserialized` attribute). This method has `StreamingContext` but it is empty and there is no possibility to fill it out with some data.

A transfer also serializes version to a journal file. Why? I don't know. It looks (thanks @mmkowal-rel  for discussion about that) that MS want to be safe in case someone creates a journal file with one version of assembly and than executes a transfer with a different version of assembly. But in that case [this line](https://github.com/relativityone/azure-storage-net-data-movement/pull/23/files#diff-20cb88e144d1175a6d22ec55b383b8a6760114bfa812aaf37324c4c7c60b5d6fL196) should throw exception before the transfer is executed. And I can't image a journal file which has two different version. In the end the decision was to remove this line at all.

2022-06-09 14:16 UTC, Pawel-Andruszkiewicz-Relativity requested changes

2022-06-09 14:16 UTC, Pawel-Andruszkiewicz-Relativity commented on netcore/DMLibTest/DMLibTest.csproj
> -    <ProjectReference Include="..\..\test\DMTestLib\DMTestLib.csproj" />
Is there a reason why it's no longer needed?

2022-06-09 14:16 UTC, Pawel-Andruszkiewicz-Relativity commented on netcore/DMLibTest/DMLibTest.csproj
> +	<ItemGroup>
Tabs instead of spaces.

2022-06-09 14:16 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/Cases/TransferContextTests.cs
> +            var stream = GetJournalStream();
I'd call it `GetOldVersionJournal()` to emphasize that your creating a journal created in old version (3.x) (but besides that's good, comprehensive suite of tests which probably was annoying to create 👍 ).

2022-06-10 06:41 UTC, KlaudiuszBryjaRelativity commented on netcore/DMLibTest/DMLibTest.csproj
> -    <ProjectReference Include="..\..\test\DMTestLib\DMTestLib.csproj" />
Look at this csproj. There are both references to netframework and netcore. IMO this is some leftover and this is the reason why this project can't be compiled on Linux.

2022-06-10 06:42 UTC, KlaudiuszBryjaRelativity commented on netcore/DMLibTest/DMLibTest.csproj
> +	<ItemGroup>
I'll look at this but it looks that we have some wrong configuration in R# and/or VS.

2022-06-10 07:12 UTC, mmkowal-rel approved these changes
apart of one issue already submitted by @Pawel-Andruszkiewicz-Relativity  nothing new found.

2022-06-10 07:12 UTC, mmkowal-rel commented on lib/Utils.cs
> +        internal static void ValidateJournalAssemblyVersion(string originalFormatVersion, string className, bool throwOnDifferentVersion)
true

2022-06-10 07:12 UTC, mmkowal-rel commented on test/DMLibTest/DMLibTest.csproj
> +    <None Include="Resources\jounal_3.1.1.0_net462.bin" />
👍

2022-06-10 09:18 UTC, KlaudiuszBryjaRelativity commented on lib/StreamJournal.cs
> +        internal bool DisableJournalAssemblyVersionValidation { get; }
Done

2022-06-10 09:19 UTC, KlaudiuszBryjaRelativity commented on test/DMLibTest/Cases/TransferContextTests.cs
> +            var stream = GetJournalStream();
Done

2022-06-10 09:24 UTC, KlaudiuszBryjaRelativity commented on lib/Utils.cs
> +        internal static void ValidateJournalAssemblyVersion(string originalFormatVersion, string className, bool throwOnDifferentVersion)
Done

2022-06-10 09:43 UTC, KlaudiuszBryjaRelativity commented on netcore/DMLibTest/DMLibTest.csproj
> +	<ItemGroup>
Done, spaces were used by MS. I formatted this file using tabs (our settings)

2022-06-10 11:59 UTC, Pawel-Andruszkiewicz-Relativity approved these changes

2022-06-10 12:08 UTC, mmkowal-rel approved these changes

2022-06-10 12:25 UTC, merged