Rel 607809 create build script
relativityone/azure-storage-net-data-movement pull request #3
Opened 2021-11-10 09:38 UTC by mbartnic-relativity

2021-11-10 13:18 UTC, KlaudiuszBryjaRelativity requested changes

2021-11-10 13:18 UTC, KlaudiuszBryjaRelativity commented on netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
> +    <SignAssembly>false</SignAssembly>
I'm not sure which sign is it: a snk or a certificate? if a snk, I'm ok with this change. If a certificate, definitely the library should be signed.

2021-11-10 13:18 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +Task default -Depends Analyze, Compile, UnitTest, Package, PublishTests, DockerTest, PublishCli -Description "Build and run unit tests (windows tests and linux tests through the container). All the s
I can see Ctrl+c and Ctrl+v method. Definitely this script need to be fixed. In my opinion this would be default: `Analyze, Compile, UnitTest, PublishTests` and maybe `Package`. It is possible that all tests need to be executed.

2021-11-10 13:18 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +Task UnitTest -Depends CoreUnitTest, AzureUnitTest, WebUnitTest -Description "Run unit tests that don't require a deployed environment.";
Review those tasks `CoreUnitTest, AzureUnitTest, WebUnitTest`. DMLib has only those tests: `DMLibTest, DMLibTest_NetStandard, DMTestLib, MsTestLib`.

2021-11-10 13:39 UTC, mbartnic-relativity commented on psakefile.ps1
> +Task DockerTest -Description "Run tests on Docker using Ubuntu .Net Core image." -Depends PublishTestsForLinux {
I had problems executing it at all from command line (due to linking of mstest visual studio library instead of nuget package); I will remove it and eventually if it will make sense

2021-11-10 13:40 UTC, mbartnic-relativity commented on test/DMLibTestCodeGen/DMLibTestCodeGen.csproj
> +    <PlatformTarget>x64</PlatformTarget>
Good catch - this was my debug effort to find cause of one problem and was suggested  by someone on the stackoverflow

2021-11-10 13:41 UTC, mbartnic-relativity commented on psakefile.ps1
> +Task BuildCoverageReport -Description "Builds Cobertura report with code coverage." {
I will remove this

2021-11-12 11:52 UTC, mbartnic-relativity commented on netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
> +    <SignAssembly>false</SignAssembly>
Currently I have no way to store safely the certificate - signing can be done after compilation when github actions will be responsible for building this and signing it

2021-11-19 09:41 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +	| Where-Object { $_.Directory.FullName -notmatch "Vendor" -and $_.Directory.FullName -notmatch "packages" -and $_.Directory.FullName -notmatch "buildtools" -and $_.Directory.FullName -notmatch "obj"
Where is a certificate?

2021-11-19 09:45 UTC, KlaudiuszBryjaRelativity requested changes

2021-11-19 09:45 UTC, KlaudiuszBryjaRelativity commented on psakefile.ps1
> +Task PublishTests -Depends PublishTestsForWindows -Description "Publish test DLLs";
Please write some information that this task is executed but not supported yet.

2021-11-19 15:49 UTC, mbartnic-relativity commented on psakefile.ps1
> +Task PublishTests -Depends PublishTestsForWindows -Description "Publish test DLLs";
I will remove it for now

2021-11-19 16:17 UTC, mbartnic-relativity commented on psakefile.ps1
> +	| Where-Object { $_.Directory.FullName -notmatch "Vendor" -and $_.Directory.FullName -notmatch "packages" -and $_.Directory.FullName -notmatch "buildtools" -and $_.Directory.FullName -notmatch "obj"
Wrote a comment about it

2021-11-22 09:39 UTC, KlaudiuszBryjaRelativity requested changes
Still need to select sln file

2021-11-22 16:03 UTC, KlaudiuszBryjaRelativity requested changes

2021-11-22 16:03 UTC, KlaudiuszBryjaRelativity commented on DataMovement.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "NetCore", "NetCore", "{2E5D799B-A7A5-4C67-9FBF-65FC568FA554}"
Please rename it to `NetStandard`

2021-11-22 16:05 UTC, Pawel-Andruszkiewicz-Relativity requested changes

2021-11-22 16:39 UTC, mbartnic-relativity commented on psakefile.ps1
> +	$Solution = ((Get-ChildItem -Path $SourceDir -Filter *.sln -File)[0].FullName)
We will have single file

2021-11-22 16:49 UTC, mbartnic-relativity commented on test/DMLibTestCodeGen/Program.cs
> +using System.Diagnostics;
Removed - byproduct of debugging

2021-11-22 16:51 UTC, mbartnic-relativity commented on test/DMLibTest_NetStandard/packages.config
> +<package>
There are discrepancies between original sln regarding this. So possibly .netcore version could be a bit different than .netstandard version. I will look into that tomorrow

2021-11-22 17:00 UTC, mbartnic-relativity commented on test/DMTestLib/DMTestLib.csproj
> +      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?Lin
This is error added automatically by VS - it will inform user that he is missing some packages (in near future disabling of restoration of packages will be removed from what I read).
This is old type of csproj, which might explain why this was added

2021-11-23 10:16 UTC, mbartnic-relativity commented on test/DMLibTest_NetStandard/app.config
> +        <assemblyIdentity name="Microsoft.Azure.KeyVault.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
I will fix this

2021-11-23 10:21 UTC, Pawel-Andruszkiewicz-Relativity commented on psakefile.ps1
> +	$Solution = ((Get-ChildItem -Path $SourceDir -Filter *.sln -File)[0].FullName)
Yeah, then leave it as is then.

2021-11-23 11:20 UTC, Pawel-Andruszkiewicz-Relativity requested changes

2021-11-23 11:20 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest_NetStandard/packages.config
> +<package>
`<package> -> <packages>` (here and at the EOF)

2021-11-23 11:21 UTC, Pawel-Andruszkiewicz-Relativity approved these changes

2021-11-23 11:23 UTC, KlaudiuszBryjaRelativity approved these changes

2021-11-23 11:46 UTC, merged