Rel 813210 revert old stuck changes v2
relativityone/azure-storage-net-data-movement pull request #35
Opened 2023-02-01 09:34 UTC by kacperniwczykr1

2023-02-01 09:58 UTC, KamilKalitaRel commented on lib/MD5HashStream.cs
> -            await this.WaitOnSemaphoreAsync(cancellationToken).ConfigureAwait(false);
I'd leave `.ConfigureAwait(false)` (in this and other places).

2023-02-01 09:58 UTC, KamilKalitaRel commented on test/DMLibTest/Cases/AllTransferDirectionTest.cs
> -            DMLibTestContext.DestType = DMLibDataType.AppendBlob;
I don't remember this changes... Was it related to some failing tests?

2023-02-01 11:16 UTC, kacperniwczykr1 commented on test/DMLibTest/Cases/AllTransferDirectionTest.cs
> -            DMLibTestContext.DestType = DMLibDataType.AppendBlob;
I would need to ask someone to help me with local test of DMLib to confirm if this doesn't affect any tests. For now I'm getting error on almost every test

2023-02-01 11:56 UTC, KlaudiuszBryjaRelativity submitted a review, later dismissed

2023-02-01 12:54 UTC, KamilKalitaRel submitted a review, later dismissed

2023-02-06 10:29 UTC, KlaudiuszBryjaRelativity requested changes

2023-02-06 10:39 UTC, kacperniwczykr1 commented on test/DMLibTest/Cases/AllTransferDirectionTest.cs
> -            DMLibTestContext.DestType = DMLibDataType.AppendBlob;
I've reverted it when I was working on my failing tests, I will revert it to old state again and re run this test case

2023-02-06 12:31 UTC, KlaudiuszBryjaRelativity commented on test/DMLibTest/Cases/AllTransferDirectionTest.cs
> -            DMLibTestContext.DestType = DMLibDataType.AppendBlob;
This line is removed. Test passed without this change.

2023-02-06 12:31 UTC, KlaudiuszBryjaRelativity approved these changes

2023-02-06 12:54 UTC, KamilKalitaRel submitted a review, later dismissed

2023-02-07 10:55 UTC, KamilKalitaRel approved these changes

2023-02-07 11:00 UTC, KlaudiuszBryjaRelativity approved these changes

2023-02-07 11:01 UTC, merged