Rel 813237 mark overwritten files
relativityone/azure-storage-net-data-movement pull request #36
Opened 2023-02-02 10:51 UTC by KamilKalitaRel

2023-02-02 15:37 UTC, KlaudiuszBryjaRelativity submitted a review, later dismissed

2023-02-03 13:52 UTC, mmkowal-rel approved these changes

2023-02-03 13:52 UTC, mmkowal-rel commented on lib/TransferControllers/TransferControllerBase.cs
> +                        this.TransferJob.IsOverwritten = true;
I'm wondering if we could simplify this translation IsOverwritten -> TransferItemStatus. 
Maybe we can have this.TransferJob.State = Overwritten

2023-02-03 13:52 UTC, mmkowal-rel commented on lib/TransferJobs/SingleObjectTransfer.cs
> +                    eventArgs.Status = this.transferJob.IsOverwritten ? TransferItemStatus.Overwritten : TransferItemStatus.Created;
related to the previous comment

2023-02-07 10:17 UTC, KamilKalitaRel commented on lib/TransferControllers/TransferControllerBase.cs
> +                        this.TransferJob.IsOverwritten = true;
Done

2023-02-07 10:17 UTC, KamilKalitaRel commented on lib/TransferJobs/SingleObjectTransfer.cs
> +                    eventArgs.Status = this.transferJob.IsOverwritten ? TransferItemStatus.Overwritten : TransferItemStatus.Created;
Done

2023-02-07 10:21 UTC, mmkowal-rel submitted a review, later dismissed

2023-02-08 07:58 UTC, KlaudiuszBryjaRelativity requested changes

2023-02-08 07:58 UTC, KlaudiuszBryjaRelativity commented on version.txt
> +4.2.9
It looks that you don't push this version to code. @mmkowal-rel updated release procedure regarding how to bump version (via script or `.\build.ps1 Package` task). # #

2023-02-08 13:15 UTC, KamilKalitaRel commented on version.txt
> +4.2.9
Done

2023-02-08 13:16 UTC, KlaudiuszBryjaRelativity approved these changes

2023-02-08 14:18 UTC, mmkowal-rel approved these changes

2023-02-08 14:46 UTC, merged