dedicated memory pool for MD5
relativityone/azure-storage-net-data-movement pull request #43
Opened 2023-09-14 12:15 UTC by kacperniwczykr1

2023-09-14 12:40 UTC, KlaudiuszBryjaRelativity requested changes

2023-09-14 12:40 UTC, KlaudiuszBryjaRelativity commented on version.txt
> +4.3.3
Please use this script `.\tools\scripts\InjectBuildNumber.ps1` to set up a valid version in all components. `Version.txt` is not enough.

2023-09-14 13:11 UTC, mmkowal-rel commented on version.txt
> +4.3.3
also please update the einstein page to track this custom change, (do it once dmlib will be released)

2023-09-14 13:15 UTC, mmkowal-rel approved these changes

2023-09-14 13:15 UTC, mmkowal-rel commented on lib/MemoryManager.cs
> +            this.md5MemoryPool = new MemoryPool(CellsCountReservedForMd5Calculation, bufferSize);
it would be good to explain in detail that this new memory pool will handle solely chunks of files that were partially transferred and interrupted in the middle of transfer
md5 calculation for new files that were not in the middle of the transfer when the transfer was interrupted remains in the main pool

2023-09-14 13:35 UTC, KamilKalitaRel commented on lib/MemoryManager.cs
> +        private const int CellsCountReservedForMd5Calculation = 8;
So the fix is to add a pool of 32 MB dedicated to MD5 calculations. Is this 8 cells enough?

Let's assume w can have 128 partly transferred files (because typically users have max 128 parallel operations), each of 2 GB total and on average 1 GB was transferred in the previous attempt.

We need to calculate the checksum for 128 GB in 4 MB chunks. We can calculate 8 at once (because there's 8 cells).

Here we can find a test, where checksum for 10 GB was calculated in ~1min. So 1 GB could be hashed in ~6 s, and 4 MB can be hashed in ~0.024 s:
https://stackoverflow.com/questions/69449472/calculate-md5-on-a-single-1t-file-or-on-100-10g-files-which-one-is-faster-or

So we will calculate checksum on 128 GB / 4 MB =32 * 1024 chunks. Each chunk allocates 1 of 8 cells, so it will be like 32 * 1024 / 8 * 0.024 s = 98 s.

Considering you enhanced the number of retries to 14 and the last waiting interval will take ~27 minutes... it seems pretty realistic. Maybe even the time margin you defined is over-pessimistic ;)

2023-09-15 10:34 UTC, mmkowal-rel approved these changes

2023-09-15 10:34 UTC, mmkowal-rel commented on lib/MemoryManager.cs
> +            this.md5MemoryPool = new MemoryPool(CellsCountReservedForMd5Calculation, bufferSize);
maybe we can rename the pool to md5RestartModeMemoryPool ?

2023-09-15 11:03 UTC, KlaudiuszBryjaRelativity approved these changes

2023-09-15 13:29 UTC, kacperniwczykr1 commented on lib/MemoryManager.cs
> +            this.md5MemoryPool = new MemoryPool(CellsCountReservedForMd5Calculation, bufferSize);
Now name itself sounds too confusing, in code there's no mention on restart mode it's only inside comments.

2023-09-15 13:30 UTC, merged