[CLI] JobId added
relativityone/azure-storage-net-data-movement pull request #52
Opened 2024-01-15 12:36 UTC by Pawel-Andruszkiewicz-Relativity

2024-01-15 12:46 UTC, KlaudiuszBryjaRelativity submitted a review, later dismissed

2024-01-15 13:30 UTC, KamilKalitaRel commented on samples/Microsoft.Azure.Storage.DataMovement.Client/CommandLineOptions.cs
> +        [Option('i', "job-id", HelpText = "JobId of the transfer (e.g. to resume it later).", Required = false)]
```suggestion
        [Option('j', "job-id", HelpText = "JobId of the transfer (e.g. to resume it later).", Required = false)]
```

`-i` is a common Unix option shortcut for an "interactive" mode. So I propose `-j`, but it's not something I will fight for relentlessly ;)

2024-01-15 13:31 UTC, KamilKalitaRel approved these changes

2024-01-15 17:34 UTC, Pawel-Andruszkiewicz-Relativity commented on samples/Microsoft.Azure.Storage.DataMovement.Client/CommandLineOptions.cs
> +        [Option('i', "job-id", HelpText = "JobId of the transfer (e.g. to resume it later).", Required = false)]
I have changed it to `-j` 👍

2024-01-16 08:56 UTC, KamilKalitaRel approved these changes

2024-01-26 11:34 UTC, KlaudiuszBryjaRelativity approved these changes

2024-01-31 10:57 UTC, KlaudiuszBryjaRelativity requested changes

2024-01-31 10:57 UTC, KlaudiuszBryjaRelativity commented on samples/Microsoft.Azure.Storage.DataMovement.Client/CommandLineOptions.cs
>          [Option('n', "transfers-number", HelpText = "Number of simultaneous transfers", Required = false, Default = 1)]
I think this parameter can be removed. It was added when we were struggling with transfer stuck. And I think it would be great to have CLI which can create and perform 1 transfer only.
If you think this is good idea to left this parameter than jobid make sense only when n equals 1.

2024-02-15 12:09 UTC, lukasz-krzykowski approved these changes

2024-04-15 16:25 UTC, closed without merging