test execution and publication
relativityone/azure-storage-net-data-movement pull request #6
Opened 2021-11-29 14:12 UTC by mbartnic-relativity

Tests should be executing
- variables are read from env variables if not provided in testdata.xml
- possibility to publish tests (there may be a bug there: under investigation)
- generation of tests for .netstandard solution
- some tests are ignored

2021-11-29 14:29 UTC, KlaudiuszBryjaRelativity requested changes

2021-11-29 14:29 UTC, KlaudiuszBryjaRelativity commented on test/DMLibTest/DMLibTest.csproj
> +	 <!--Condition=" '$(Mode)' == 'Full' " -->
Remove this comment

2021-11-29 14:29 UTC, KlaudiuszBryjaRelativity commented on test/DMLibTest/TestData.xml
> -  <StorageConnectionString>DefaultEndpointsProtocol=https;AccountName=testaccount1;AccountKey=FjUfNl1KiJttbXlsdkMzBTC7WagvrRM9/g6UPBuy0ypCpAbYTL6/KA+dI/7gyoWvLFYmah3IviUP1jykOHHOlA==;BlobEndpoint=htt
Why do you remove those connection strings?

2021-11-29 15:34 UTC, mbartnic-relativity commented on test/DMLibTest/TestData.xml
> -  <StorageConnectionString>DefaultEndpointsProtocol=https;AccountName=testaccount1;AccountKey=FjUfNl1KiJttbXlsdkMzBTC7WagvrRM9/g6UPBuy0ypCpAbYTL6/KA+dI/7gyoWvLFYmah3IviUP1jykOHHOlA==;BlobEndpoint=htt
Those are old obsolete connection strings (from MS repository). Currently if those values won't be found - we have a logic that would get this data from environmental variables.

2021-11-30 08:46 UTC, KlaudiuszBryjaRelativity approved these changes

2021-11-30 11:52 UTC, KamilKalitaRel approved these changes

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity requested changes

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity commented on psakefile.ps1
> +	$variableNames = @("DM_LIB_CONNECTION_STRING_SOURCE", "DM_LIB_CONNECTION_STRING_DESTINATION", "DESTINATION_ENCRYPTION_SCOPE")
These are environmental constants, right? If so, these vars are expected to be present on our dev machines, do we need/want to change it? 

I'm asking cos I'm lazy and I don't want to change these env names because these names are since the project has started, they are referenced on Einstein, probably on Trident, etc. - having new names without checking mentioned places might bring mess.

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/Cases/AccessConditionTest.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
Using outside of namespace.

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
What's that?

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/DMLibTest.csproj
> +    <Exec Command="$(CodeGenPath)$(OutputPath)DMLibTestCodeGen.exe $(MSBuildProjectDirectory)\$(OutputPath)$(AssemblyName).dll $(SourceCodeOuputFolder) DNet" />
DNet?

2021-11-30 13:54 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMTestLib/MultiDirectionTestClassAttribute.cs
> +        public bool Ignore { get; set; }
This ignore will result in test case generation or test case execution? 

If first - how long does it take to generate all tests?
If latter - can you please sync up with @BartoszWierzbaRelativity with the approach how do you want to handle marking what tests should be ignored? 

I'm not saying this is bad, but I don't want to end up in a scenario where some of the tests are not even generated, others are but are ignored, and on top of that we have the attribute that specifies what tests should be executed by our pipeline. It would be a mess.

If generation doesn't take long, I'd generate all the tests, and then mark with custom attribute (e.g. "TAPI Selected Tests") which ones do we actually want to invoke in `psakebuild.ps1 RunTests`.

If marking with would be problematic (e.g. it's hard to mark them after they are generated), let's go with Ignore attribute before they are even generated, but consider naming (`Ignore` doesn't tell us why they are ignored, I'd add `IgnoredByTapi` or `IgnoredNotUsedFeature`), unless you plan to put the description elsewhere and I just don't see it yet?

2021-11-30 14:30 UTC, mbartnic-relativity commented on netcore/DMLibTest/TestData.xml
> +  <StorageConnectionString></StorageConnectionString>
Yes, they are used in tests and will be passed as environmental variables

2021-11-30 14:32 UTC, mbartnic-relativity commented on test/DMLibTest/DMLibTest.csproj
> +    <Exec Command="$(CodeGenPath)$(OutputPath)DMLibTestCodeGen.exe $(MSBuildProjectDirectory)\$(OutputPath)$(AssemblyName).dll $(SourceCodeOuputFolder) DNet" />
Code generator has an enum which in case of this value will generate .net framework tests

2021-11-30 14:36 UTC, mbartnic-relativity commented on test/DMTestLib/MultiDirectionTestClassAttribute.cs
> +        public bool Ignore { get; set; }
Generation of test cases is few seconds long.

@BartoszWierzbaRelativity has done this functionality and I think it will ignore generated test case. @BartoszWierzbaRelativity please correct me if I am wrong.

Bartosz could you add ignore reason here also?

2021-11-30 14:38 UTC, mbartnic-relativity commented on test/DMLibTest/Cases/AccessConditionTest.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
Oh no! 😱

2021-11-30 14:40 UTC, mbartnic-relativity commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
@KamilKalitaRel could you explain?

2021-11-30 14:40 UTC, BartoszWierzbaRelativity commented on test/DMTestLib/MultiDirectionTestClassAttribute.cs
> +        public bool Ignore { get; set; }
Generating tests takes a couple of seconds.

This Ignore doesn't affect generating tests but it adds an attribute that causes generated test to be skipped.

Initial assumption was that we will ignore problematic or unnecessary tests with this property and it should work for this usecase similarly as nunit ignore works in TAPI.

2021-11-30 14:47 UTC, KamilKalitaRel commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
It's good you noticed that, Paweł. It was required to run this suite on .NET Core. Adding a suite to the Global collection effects with an one-time initialization (like initialization of the logger). In .NET Core it's used instead of Assembly Init. 

It seems to be required on every suite, unless you run many of them with the first one run with this attribute. So it's the question: do we want to leave it as it is, or do we plan to run .NET Core generated tests only as a whole set of suites?

2021-11-30 14:54 UTC, mbartnic-relativity commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
For now I would leave it as it is - creating our own test suite should be done in another story - this one already took too long

2021-11-30 14:55 UTC, mbartnic-relativity commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
Furthermore: we need to identify tests that we will want to run always in the first place. @mmkowal-rel or @KlaudiuszBryjaRelativity should know the scope I think.

2021-11-30 15:08 UTC, BartoszWierzbaRelativity commented on test/DMTestLib/MultiDirectionTestClassAttribute.cs
> +        public bool Ignore { get; set; }
Added IgnoredByTapi message to ignore attributes.

@Pawel-Andruszkiewicz-Relativity this mechanism can be adjusted to the scenario which will emerge from tests analysis. For now we wanted something that is simple and works.

2021-11-30 20:13 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/Cases/LongFilePathTest.cs
> +    [Collection(Collections.Global)]
I agree that's outside of current's story scope and I'm okay to leave it as is if it doesn't break anything (as I don't fully understand the consequences of it) and a new story for scoping the tests for our needs is created (just a draft, we can groom it later, i.e. on tech discussion). Can one of you please create it?

2021-11-30 20:13 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMLibTest/Cases/AccessConditionTest.cs
> +using Microsoft.VisualStudio.TestTools.UnitTesting;
: )

2021-11-30 20:13 UTC, Pawel-Andruszkiewicz-Relativity commented on test/DMTestLib/MultiDirectionTestClassAttribute.cs
> +        public bool Ignore { get; set; }
Sure, the simpler it is the better. The point is that:
- `Ignore` might look like it comes from the Microsoft itself, not us. It's obvious for us, but in a year, when half of the team rotates, it might no longer be that obvious. If it's going to be marked as a comment similarly as in NUnit (i.e. `[Ignore("Ignored as this feature is not used by TAPI")]`) I'm okay with it.
- I wanted to ensure we either go with Ignore, or with `Category` approach (on today's call we leaned towards the latter), not both.

2021-12-01 10:15 UTC, Pawel-Andruszkiewicz-Relativity approved these changes

2021-12-01 10:55 UTC, merged