[DM-1] readme update
relativityone/azure-storage-net-data-movement pull request #9
Opened 2021-12-01 16:34 UTC by mbartnic-relativity

2021-12-01 17:15 UTC, KlaudiuszBryjaRelativity requested changes

2021-12-01 17:15 UTC, KlaudiuszBryjaRelativity commented on README.md
> +Security fixes made on the original will merged to this repository.
...will be merged...

2021-12-01 17:25 UTC, mbartnic-relativity commented on README.md
> +Security fixes made on the original will merged to this repository.
Thanks, fixed

2021-12-03 08:23 UTC, KlaudiuszBryjaRelativity approved these changes

2021-12-03 09:00 UTC, merged